spring.application.name=issue-tracker
spring.datasource.url=jdbc:mysql://localhost:3306/issuetracker
spring.datasource.username=root
spring.datasource.password=VINAY@gieta630
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true